apiVersion: v1
kind: Service

spec:
    ports:
        - port: 80
          targetPort: 9000
          protocol: TCP
          name: http
---
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: grpc-hello
        spec:
            containers:
                - name: esp
                  ports:
                      - containerPort: 9000
